INSERT INTO "public"."competencies" ("id", "created_at", "title", "subtitle", "icon", "items", "color_theme", "display_order") VALUES ('a1c1e9f0-0001-4b01-9e00-000000000001', '2026-01-28 21:35:57.26971+00', 'Consultoria & Estratégia', 'Análise, planejamento e direcionamento tecnológico.', 'fa-solid fa-handshake', ARRAY["Consultoria em TI e Estratégia","Roadmap tecnológico personalizado","Otimização de processos e governança","Recomendações estratégicas sob medida"], 'purple', '1'), ('a1c1e9f0-0002-4b01-9e00-000000000002', '2026-01-28 21:35:57.26971+00', 'Gestão & Liderança', 'Condução de projetos e equipes com foco em resultados.', 'fa-solid fa-users-gear', ARRAY["Gestão Estratégica de Projetos","Metodologias Ágeis e Tradicionais","Liderança de equipes e gestão de conflitos","Ambiente produtivo e colaborativo"], 'green', '2'), ('a1c1e9f0-0003-4b01-9e00-000000000003', '2026-01-28 21:35:57.26971+00', 'Desenvolvimento de Sistemas', 'Soluções sob medida para web e mobile.', 'fa-solid fa-laptop-code', ARRAY["Sistemas Web e Mobile sob medida","Planejamento, desenvolvimento e entrega","Tecnologias: Python, PHP, JavaScript, MySQL","Soluções escaláveis e robustas"], 'indigo', '3'), ('a1c1e9f0-0004-4b01-9e00-000000000004', '2026-01-28 21:35:57.26971+00', 'Arquitetura & Operações', 'Soluções robustas, seguras e eficientes para escalar seu negócio.', 'fa-solid fa-sitemap', ARRAY["Design de sistemas complexos","Governança de TI e Cloud (AWS, Azure)","Gestão de Riscos e Continuidade Operacional","Otimização de Processos e Redução de Gargalos"], 'gray', '4');


/* ---------------------------- outros idiomas ---------------------------- */

INSERT INTO "public"."competencies" (
  "id", 
  "created_at", 
  "title", 
  "title_pt", 
  "title_en", 
  "title_fr",
  "subtitle", 
  "subtitle_pt", 
  "subtitle_en", 
  "subtitle_fr",
  "icon", 
  "items", 
  "items_pt", 
  "items_en", 
  "items_fr",
  "color_theme", 
  "display_order"
) VALUES 
(
  'a1c1e9f0-0001-4b01-9e00-000000000001', 
  '2026-01-28 21:35:57.26971+00', 
  'Consultoria & Estratégia',
  'Consultoria & Estratégia',
  'Consulting & Strategy',
  'Conseil & Stratégie',
  'Análise, planejamento e direcionamento tecnológico.',
  'Análise, planejamento e direcionamento tecnológico.',
  'Analysis, planning and technological direction.',
  'Analyse, planification et orientation technologique.',
  'fa-solid fa-handshake', 
  ARRAY['Consultoria em TI e Estratégia','Roadmap tecnológico personalizado','Otimização de processos e governança','Recomendações estratégicas sob medida'],
  ARRAY['Consultoria em TI e Estratégia','Roadmap tecnológico personalizado','Otimização de processos e governança','Recomendações estratégicas sob medida'],
  ARRAY['IT and Strategy Consulting','Customized technology roadmap','Process optimization and governance','Tailored strategic recommendations'],
  ARRAY['Conseil en TI et Stratégie','Feuille de route technologique personnalisée','Optimisation des processus et gouvernance','Recommandations stratégiques sur mesure'],
  'purple', 
  1
),
(
  'a1c1e9f0-0002-4b01-9e00-000000000002', 
  '2026-01-28 21:35:57.26971+00', 
  'Gestão & Liderança',
  'Gestão & Liderança',
  'Management & Leadership',
  'Gestion & Leadership',
  'Condução de projetos e equipes com foco em resultados.',
  'Condução de projetos e equipes com foco em resultados.',
  'Leading projects and teams with a focus on results.',
  'Conduite de projets et d\'équipes axée sur les résultats.',
  'fa-solid fa-users-gear', 
  ARRAY['Gestão Estratégica de Projetos','Metodologias Ágeis e Tradicionais','Liderança de equipes e gestão de conflitos','Ambiente produtivo e colaborativo'],
  ARRAY['Gestão Estratégica de Projetos','Metodologias Ágeis e Tradicionais','Liderança de equipes e gestão de conflitos','Ambiente produtivo e colaborativo'],
  ARRAY['Strategic Project Management','Agile and Traditional Methodologies','Team leadership and conflict management','Productive and collaborative environment'],
  ARRAY['Gestion Stratégique de Projets','Méthodologies Agiles et Traditionnelles','Leadership d\'équipe et gestion des conflits','Environnement productif et collaboratif'],
  'green', 
  2
),
(
  'a1c1e9f0-0003-4b01-9e00-000000000003', 
  '2026-01-28 21:35:57.26971+00', 
  'Desenvolvimento de Sistemas',
  'Desenvolvimento de Sistemas',
  'Systems Development',
  'Développement de Systèmes',
  'Soluções sob medida para web e mobile.',
  'Soluções sob medida para web e mobile.',
  'Customized solutions for web and mobile.',
  'Solutions sur mesure pour web et mobile.',
  'fa-solid fa-laptop-code', 
  ARRAY['Sistemas Web e Mobile sob medida','Planejamento, desenvolvimento e entrega','Tecnologias: Python, PHP, JavaScript, MySQL','Soluções escaláveis e robustas'],
  ARRAY['Sistemas Web e Mobile sob medida','Planejamento, desenvolvimento e entrega','Tecnologias: Python, PHP, JavaScript, MySQL','Soluções escaláveis e robustas'],
  ARRAY['Custom Web and Mobile Systems','Planning, development and delivery','Technologies: Python, PHP, JavaScript, MySQL','Scalable and robust solutions'],
  ARRAY['Systèmes Web et Mobile sur mesure','Planification, développement et livraison','Technologies: Python, PHP, JavaScript, MySQL','Solutions évolutives et robustes'],
  'indigo', 
  3
),
(
  'a1c1e9f0-0004-4b01-9e00-000000000004', 
  '2026-01-28 21:35:57.26971+00', 
  'Arquitetura & Operações',
  'Arquitetura & Operações',
  'Architecture & Operations',
  'Architecture & Opérations',
  'Soluções robustas, seguras e eficientes para escalar seu negócio.',
  'Soluções robustas, seguras e eficientes para escalar seu negócio.',
  'Robust, secure and efficient solutions to scale your business.',
  'Solutions robustes, sécurisées et efficaces pour faire évoluer votre entreprise.',
  'fa-solid fa-sitemap', 
  ARRAY['Design de sistemas complexos','Governança de TI e Cloud (AWS, Azure)','Gestão de Riscos e Continuidade Operacional','Otimização de Processos e Redução de Gargalos'],
  ARRAY['Design de sistemas complexos','Governança de TI e Cloud (AWS, Azure)','Gestão de Riscos e Continuidade Operacional','Otimização de Processos e Redução de Gargalos'],
  ARRAY['Complex systems design','IT Governance and Cloud (AWS, Azure)','Risk Management and Operational Continuity','Process Optimization and Bottleneck Reduction'],
  ARRAY['Conception de systèmes complexes','Gouvernance TI et Cloud (AWS, Azure)','Gestion des Risques et Continuité Opérationnelle','Optimisation des Processus et Réduction des Goulets'],
  'gray', 
  4
);
