INSERT INTO "public"."journey_items" ("id", "created_at", "title", "company", "period", "description", "type", "display_order") VALUES ('0e86885d-a897-4c6f-8016-8a3d523a466b', '2026-01-20 22:58:00.45945+00', 'Estagiário', 'COTEMIG', 'Mai de 2017 – Dez de 2017', 'Atuei como monitor e suporte técnico, auxiliando alunos com dúvidas em diversas linguagens de programação (HTML, JavaScript/jQuery, MySQL, C#, ASP.Net e PHP), redes e arquitetura, contribuindo para o aprendizado e desenvolvimento técnico.', 'experience', '5'), ('2390a1f9-5b1a-4643-b109-006614f3ba18', '2026-01-20 22:58:00.45945+00', 'Oficial do Exército Brasileiro (1º Tenente e Subcomandante)', 'Exército Brasileiro', 'Set de 2023 – Atual (7 anos de experiência militar)', 'Líder com 7 anos de experiência em comando, gestão estratégica, logística, operações e governança. Atuo como Subcomandante, principal líder e assessor direto do Comandante, responsável pela liderança institucional, gestão operacional e de pessoas, e assessoramento estratégico para tomada de decisão em ambientes de alta pressão. Experiência em gestão de riscos, licitações e contratos, e planejamento de missões de apoio à sociedade.', 'experience', '0'), ('33bceecc-27d1-439d-a27c-7e372a038deb', '2026-01-20 22:58:00.45945+00', 'Gerente de Projetos', '2C SISTEMAS', 'Fev de 2017 – Mai de 2020', 'Liderei o desenvolvimento de um sistema de gerenciamento de tarefas para a Embrapa Gado de Leite, arquitetando o sistema do zero, levantando requisitos, modelando banco de dados e desenvolvendo o backend (jQuery, MySQL, AJAX, JavaScript e PHP). Fui responsável pela gestão completa do projeto e implantação da infraestrutura.', 'experience', '2'), ('6464a78a-a4a5-40cb-9edd-8e9b2ace445f', '2026-01-20 22:58:00.45945+00', 'Técnico em Informática', 'Colégio COTEMIG', '2016 – 2017', 'Ensino médio integrado ao curso técnico, proporcionando aprofundamento em TI e experiência prática. Participei como expositor na FINIT (Feira Internacional de Negócios, Inovação e Tecnologia) em 2017.', 'education', '6'), ('9882e315-3707-4f57-9057-4fa346a47083', '2026-01-20 22:58:00.45945+00', 'Desenvolvedor Júnior', 'Brasiltrack Monitoramento Via Satélite', 'Jan de 2018 – Fev de 2019', 'Atuei na análise, desenvolvimento e manutenção de sistemas de monitoramento logístico (jQuery, MySQL, AJAX, JavaScript e PHP). Desenvolvi e mantive Gateways para comunicação com rastreadores e APIs em Python para integração entre sistemas.', 'experience', '4'), ('997a6fcd-e7e5-4ac9-8f63-dfd5335722a2', '2026-01-20 22:58:00.45945+00', 'MBA em Inteligência Artificial e Gestão de Negócios', 'Gran Faculdade', 'Nov de 2025 – Mai de 2027 (Em Conclusão)', 'Foco em aliar gestão estratégica e inovação com as mais recentes tecnologias em IA, capacitando para liderança da transformação digital e geração de valor competitivo.', 'education', '1'), ('cbdb98c4-42ee-49a3-9513-b02f08492541', '2026-01-20 22:58:00.45945+00', 'Graduação em Análise e Desenvolvimento de Sistemas', 'Estácio', 'Jan de 2022 – Abr de 2024', 'Formação sólida em desenvolvimento de software, gestão de projetos, banco de dados, programação orientada a objetos (POO) e análise de requisitos.', 'education', '3');


/* ---------------------------- outros idiomas ---------------------------- */

INSERT INTO "public"."journey_items" (
  "id", "created_at",
  "title", "title_pt", "title_en", "title_fr",
  "company", "company_pt", "company_en", "company_fr",
  "period", "period_pt", "period_en", "period_fr",
  "description", "description_pt", "description_en", "description_fr",
  "type", "display_order"
) VALUES
(
  '0e86885d-a897-4c6f-8016-8a3d523a466b',
  '2026-01-20 22:58:00.45945+00',
  'Estagiário',
  'Estagiário',
  'Intern',
  'Stagiaire',
  'COTEMIG',
  'COTEMIG',
  'COTEMIG',
  'COTEMIG',
  'Mai de 2017 – Dez de 2017',
  'Mai de 2017 – Dez de 2017',
  'May 2017 – Dec 2017',
  'Mai 2017 – Déc 2017',
  'Atuei como monitor e suporte técnico, auxiliando alunos com dúvidas em diversas linguagens de programação (HTML, JavaScript/jQuery, MySQL, C#, ASP.Net e PHP), redes e arquitetura, contribuindo para o aprendizado e desenvolvimento técnico.',
  'Atuei como monitor e suporte técnico, auxiliando alunos com dúvidas em diversas linguagens de programação (HTML, JavaScript/jQuery, MySQL, C#, ASP.Net e PHP), redes e arquitetura, contribuindo para o aprendizado e desenvolvimento técnico.',
  'Worked as a lab monitor and technical support, helping students with questions in several programming languages (HTML, JavaScript/jQuery, MySQL, C#, ASP.Net and PHP), networks and architecture, contributing to their learning and technical development.',
  'J\'ai travaillé comme moniteur et support technique, aidant les étudiants avec des questions sur plusieurs langages de programmation (HTML, JavaScript/jQuery, MySQL, C#, ASP.Net et PHP), réseaux et architecture, contribuant à leur apprentissage et développement technique.',
  'experience',
  5
),
(
  '2390a1f9-5b1a-4643-b109-006614f3ba18',
  '2026-01-20 22:58:00.45945+00',
  'Oficial do Exército Brasileiro (1º Tenente e Subcomandante)',
  'Oficial do Exército Brasileiro (1º Tenente e Subcomandante)',
  'Brazilian Army Officer (First Lieutenant and Deputy Commander)',
  'Officier de l’Armée Brésilienne (Lieutenant de première classe et Sous-commandant)',
  'Exército Brasileiro',
  'Exército Brasileiro',
  'Brazilian Army',
  'Armée Brésilienne',
  'Set de 2023 – Atual (7 anos de experiência militar)',
  'Set de 2023 – Atual (7 anos de experiência militar)',
  'Sep 2023 – Present (7 years of military experience)',
  'Sept 2023 – Présent (7 ans d’expérience militaire)',
  'Líder com 7 anos de experiência em comando, gestão estratégica, logística, operações e governança. Atuo como Subcomandante, principal líder e assessor direto do Comandante, responsável pela liderança institucional, gestão operacional e de pessoas, e assessoramento estratégico para tomada de decisão em ambientes de alta pressão. Experiência em gestão de riscos, licitações e contratos, e planejamento de missões de apoio à sociedade.',
  'Líder com 7 anos de experiência em comando, gestão estratégica, logística, operações e governança. Atuo como Subcomandante, principal líder e assessor direto do Comandante, responsável pela liderança institucional, gestão operacional e de pessoas, e assessoramento estratégico para tomada de decisão em ambientes de alta pressão. Experiência em gestão de riscos, licitações e contratos, e planejamento de missões de apoio à sociedade.',
  'Leader with 7 years of experience in command, strategic management, logistics, operations and governance. I serve as Deputy Commander, the main leader and direct adviser to the Commander, responsible for institutional leadership, operational and people management, and strategic advisory for decision-making in high-pressure environments. Experience in risk management, public tenders and contracts, and planning missions to support society.',
  'Leader avec 7 ans d’expérience en commandement, gestion stratégique, logistique, opérations et gouvernance. J\'agis comme Sous-commandant, principal leader et conseiller direct du Commandant, responsable du leadership institutionnel, de la gestion opérationnelle et des personnes, ainsi que du conseil stratégique pour la prise de décision dans des environnements à forte pression. Expérience en gestion des risques, appels d’offres et contrats, et planification de missions de soutien à la société.',
  'experience',
  0
),
(
  '33bceecc-27d1-439d-a27c-7e372a038deb',
  '2026-01-20 22:58:00.45945+00',
  'Gerente de Projetos',
  'Gerente de Projetos',
  'Project Manager',
  'Chef de Projet',
  '2C SISTEMAS',
  '2C SISTEMAS',
  '2C SISTEMAS',
  '2C SISTEMAS',
  'Fev de 2017 – Mai de 2020',
  'Fev de 2017 – Mai de 2020',
  'Feb 2017 – May 2020',
  'Fév 2017 – Mai 2020',
  'Liderei o desenvolvimento de um sistema de gerenciamento de tarefas para a Embrapa Gado de Leite, arquitetando o sistema do zero, levantando requisitos, modelando banco de dados e desenvolvendo o backend (jQuery, MySQL, AJAX, JavaScript e PHP). Fui responsável pela gestão completa do projeto e implantação da infraestrutura.',
  'Liderei o desenvolvimento de um sistema de gerenciamento de tarefas para a Embrapa Gado de Leite, arquitetando o sistema do zero, levantando requisitos, modelando banco de dados e desenvolvendo o backend (jQuery, MySQL, AJAX, JavaScript e PHP). Fui responsável pela gestão completa do projeto e implantação da infraestrutura.',
  'Led the development of a task management system for Embrapa Gado de Leite, architecting the system from scratch, gathering requirements, modeling the database and developing the backend (jQuery, MySQL, AJAX, JavaScript and PHP). Was responsible for full project management and infrastructure deployment.',
  'J\'ai dirigé le développement d\'un système de gestion de tâches pour Embrapa Gado de Leite, en architecturant le système depuis zéro, en levantant les exigences, en modélisant la base de données et en développant le backend (jQuery, MySQL, AJAX, JavaScript et PHP). J\'ai été responsable de la gestion complète du projet et du déploiement de l’infrastructure.',
  'experience',
  2
),
(
  '6464a78a-a4a5-40cb-9edd-8e9b2ace445f',
  '2026-01-20 22:58:00.45945+00',
  'Técnico em Informática',
  'Técnico em Informática',
  'IT Technician',
  'Technicien en Informatique',
  'Colégio COTEMIG',
  'Colégio COTEMIG',
  'COTEMIG High School',
  'Lycée COTEMIG',
  '2016 – 2017',
  '2016 – 2017',
  '2016 – 2017',
  '2016 – 2017',
  'Ensino médio integrado ao curso técnico, proporcionando aprofundamento em TI e experiência prática. Participei como expositor na FINIT (Feira Internacional de Negócios, Inovação e Tecnologia) em 2017.',
  'Ensino médio integrado ao curso técnico, proporcionando aprofundamento em TI e experiência prática. Participei como expositor na FINIT (Feira Internacional de Negócios, Inovação e Tecnologia) em 2017.',
  'High school integrated with a technical IT course, providing deeper knowledge in IT and hands-on experience. Participated as an exhibitor at FINIT (International Fair of Business, Innovation and Technology) in 2017.',
  'Lycée intégré à une formation technique en informatique, offrant un approfondissement en TI et une expérience pratique. J\'ai participé comme exposant à la FINIT (Foire Internationale des Affaires, de l’Innovation et de la Technologie) en 2017.',
  'education',
  6
),
(
  '9882e315-3707-4f57-9057-4fa346a47083',
  '2026-01-20 22:58:00.45945+00',
  'Desenvolvedor Júnior',
  'Desenvolvedor Júnior',
  'Junior Developer',
  'Développeur Junior',
  'Brasiltrack Monitoramento Via Satélite',
  'Brasiltrack Monitoramento Via Satélite',
  'Brasiltrack Satellite Monitoring',
  'Brasiltrack Surveillance par Satellite',
  'Jan de 2018 – Fev de 2019',
  'Jan de 2018 – Fev de 2019',
  'Jan 2018 – Feb 2019',
  'Jan 2018 – Fév 2019',
  'Atuei na análise, desenvolvimento e manutenção de sistemas de monitoramento logístico (jQuery, MySQL, AJAX, JavaScript e PHP). Desenvolvi e mantive Gateways para comunicação com rastreadores e APIs em Python para integração entre sistemas.',
  'Atuei na análise, desenvolvimento e manutenção de sistemas de monitoramento logístico (jQuery, MySQL, AJAX, JavaScript e PHP). Desenvolvi e mantive Gateways para comunicação com rastreadores e APIs em Python para integração entre sistemas.',
  'Worked on analysis, development and maintenance of logistics monitoring systems (jQuery, MySQL, AJAX, JavaScript and PHP). Developed and maintained gateways for communication with trackers and Python APIs for system integration.',
  'J\'ai travaillé sur l\'analyse, le développement et la maintenance de systèmes de suivi logistique (jQuery, MySQL, AJAX, JavaScript et PHP). J\'ai développé et maintenu des passerelles pour la communication avec les traceurs et des API en Python pour l\'intégration entre systèmes.',
  'experience',
  4
),
(
  '997a6fcd-e7e5-4ac9-8f63-dfd5335722a2',
  '2026-01-20 22:58:00.45945+00',
  'MBA em Inteligência Artificial e Gestão de Negócios',
  'MBA em Inteligência Artificial e Gestão de Negócios',
  'MBA in Artificial Intelligence and Business Management',
  'MBA en Intelligence Artificielle et Gestion des Affaires',
  'Gran Faculdade',
  'Gran Faculdade',
  'Gran College',
  'Gran Faculté',
  'Nov de 2025 – Mai de 2027 (Em Conclusão)',
  'Nov de 2025 – Mai de 2027 (Em Conclusão)',
  'Nov 2025 – May 2027 (In Progress)',
  'Nov 2025 – Mai 2027 (En Cours)',
  'Foco em aliar gestão estratégica e inovação com as mais recentes tecnologias em IA, capacitando para liderança da transformação digital e geração de valor competitivo.',
  'Foco em aliar gestão estratégica e inovação com as mais recentes tecnologias em IA, capacitando para liderança da transformação digital e geração de valor competitivo.',
  'Focus on combining strategic management and innovation with the latest AI technologies, enabling leadership of digital transformation and generation of competitive value.',
  'Accent sur la combinaison de la gestion stratégique et de l\'innovation avec les technologies d’IA les plus récentes, permettant de conduire la transformation digitale et de générer de la valeur compétitive.',
  'education',
  1
),
(
  'cbdb98c4-42ee-49a3-9513-b02f08492541',
  '2026-01-20 22:58:00.45945+00',
  'Graduação em Análise e Desenvolvimento de Sistemas',
  'Graduação em Análise e Desenvolvimento de Sistemas',
  'Bachelor in Systems Analysis and Development',
  'Licence en Analyse et Développement de Systèmes',
  'Estácio',
  'Estácio',
  'Estácio',
  'Estácio',
  'Jan de 2022 – Abr de 2024',
  'Jan de 2022 – Abr de 2024',
  'Jan 2022 – Apr 2024',
  'Jan 2022 – Avr 2024',
  'Formação sólida em desenvolvimento de software, gestão de projetos, banco de dados, programação orientada a objetos (POO) e análise de requisitos.',
  'Formação sólida em desenvolvimento de software, gestão de projetos, banco de dados, programação orientada a objetos (POO) e análise de requisitos.',
  'Solid background in software development, project management, databases, object-oriented programming (OOP) and requirements analysis.',
  'Formation solide en développement logiciel, gestion de projets, bases de données, programmation orientée objet (POO) et analyse des exigences.',
  'education',
  3
);
