INSERT INTO "public"."projects" ("id", "created_at", "title", "role", "description", "technologies", "github_url", "live_url", "image_url", "display_order") VALUES ('4a0b53ed-c1a2-4e4f-bb38-27d8d25e6e0f', '2026-01-20 20:04:02.003325+00', 'Marçal Treinos', 'Fullstack Developer', 'Sistema completo de gestão de fichas de alunos (Web/Mobile). Features: Login Google, Acesso individual, Progressão de treino e Integração MercadoPago.', '{''React'',''Node.js'',''Firebase'',"''MercadoPago API''"}', 'https://github.com/igormatos', '#', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop', '2'), ('94ab1975-1200-4929-b06c-59d02d075f45', '2026-01-20 20:04:02.003325+00', 'Sistema de Gestão para a Embrapa Gado de Leite', 'Frontend Lead', 'Sistema de gestão de tarefas otimizado para o setor lácteo, desenvolvido em parceria com o Colégio Cotemig.', '{''Vue.js'',"''.NET Core''","''SQL Server''"}', 'https://github.com/igormatos', '#', 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?q=80&w=1474&auto=format&fit=crop', '0'), ('e2cf4875-35fb-4345-a693-7b9c2a1465fd', '2026-01-20 20:04:02.003325+00', 'Arquitetura 2C Sistemas', 'Solutions Architect', 'Atuação como PM e Arquiteto na reestruturação de sistemas legados e implementação de novos processos de CI/CD.', '{''Docker'',''AWS'',''Microservices''}', '', '#', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1472&auto=format&fit=crop', '1');

INSERT INTO "public"."projects" (
  "id", "created_at",
  "title", "title_pt", "title_en", "title_fr",
  "role", "role_pt", "role_en", "role_fr",
  "description", "description_pt", "description_en", "description_fr",
  "technologies", "technologies_pt", "technologies_en", "technologies_fr",
  "github_url", "live_url", "image_url", "display_order"
) VALUES
(
  '4a0b53ed-c1a2-4e4f-bb38-27d8d25e6e0f',
  '2026-01-20 20:04:02.003325+00',
  'Marçal Treinos',
  'Marçal Treinos',
  'Marçal Training',
  'Marçal Entraînement',
  'Fullstack Developer',
  'Desenvolvedor Fullstack',
  'Fullstack Developer',
  'Développeur Fullstack',
  'Sistema completo de gestão de fichas de alunos (Web/Mobile). Features: Login Google, Acesso individual, Progressão de treino e Integração MercadoPago.',
  'Sistema completo de gestão de fichas de alunos (Web/Mobile). Features: Login Google, Acesso individual, Progressão de treino e Integração MercadoPago.',
  'Complete student sheet management system (Web/Mobile). Features: Google Login, Individual access, Training progression and MercadoPago integration.',
  'Système complet de gestion de fiches d''étudiants (Web/Mobile). Fonctionnalités: Connexion Google, Accès individuel, Progression d''entraînement et Intégration MercadoPago.',
  'React, Node.js, Firebase, MercadoPago API',
  'React, Node.js, Firebase, MercadoPago API',
  'React, Node.js, Firebase, MercadoPago API',
  'React, Node.js, Firebase, MercadoPago API',
  'https://github.com/igormmatos',
  '#',
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop',
  2
),
(
  '94ab1975-1200-4929-b06c-59d02d075f45',
  '2026-01-20 20:04:02.003325+00',
  'Sistema de Gestão para a Embrapa Gado de Leite',
  'Sistema de Gestão para a Embrapa Gado de Leite',
  'Management System for Embrapa Dairy Cattle',
  'Système de Gestion pour Embrapa Bovins Laitiers',
  'Frontend Lead',
  'Líder de Frontend',
  'Frontend Lead',
  'Responsable Frontend',
  'Sistema de gestão de tarefas otimizado para o setor lácteo, desenvolvido em parceria com o Colégio Cotemig.',
  'Sistema de gestão de tarefas otimizado para o setor lácteo, desenvolvido em parceria com o Colégio Cotemig.',
  'Task management system optimized for the dairy sector, developed in partnership with Colégio Cotemig.',
  'Système de gestion de tâches optimisé pour le secteur laitier, développé en partenariat avec Colégio Cotemig.',
  'Vue.js, .NET Core, SQL Server',
  'Vue.js, .NET Core, SQL Server',
  'Vue.js, .NET Core, SQL Server',
  'Vue.js, .NET Core, SQL Server',
  'https://github.com/igormmatos',
  '#',
  'https://images.unsplash.com/photo-1500595046743-cd271d694d30?q=80&w=1474&auto=format&fit=crop',
  0
),
(
  'e2cf4875-35fb-4345-a693-7b9c2a1465fd',
  '2026-01-20 20:04:02.003325+00',
  'Arquitetura 2C Sistemas',
  'Arquitetura 2C Sistemas',
  '2C Systems Architecture',
  'Architecture 2C Systèmes',
  'Solutions Architect',
  'Arquiteto de Soluções',
  'Solutions Architect',
  'Architecte de Solutions',
  'Atuação como PM e Arquiteto na reestruturação de sistemas legados e implementação de novos processos de CI/CD.',
  'Atuação como PM e Arquiteto na reestruturação de sistemas legados e implementação de novos processos de CI/CD.',
  'Worked as PM and Architect in the restructuring of legacy systems and implementation of new CI/CD processes.',
  'Travail en tant que PM et Architecte dans la restructuration de systèmes hérités et la mise en œuvre de nouveaux processus CI/CD.',
  'Docker, AWS, Microservices',
  'Docker, AWS, Microservices',
  'Docker, AWS, Microservices',
  'Docker, AWS, Microservices',
  '',
  '#',
  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1472&auto=format&fit=crop',
  1
);
